name: build-and-publish-pypi

on:
  release:
    types: [published]

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        id: checkout
        uses: actions/checkout@v4
      -
        name: setup-python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      -
        name: install-packages
        id: install-packages
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      -
        name: build-package
        id: build-package
        run: |
          python -m build
      -
        name: upload-package
        id: upload-package
        uses: actions/upload-artifact@v4
        with:
          path: dist/
  publish-package:
    needs:
      - build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/psifx
    permissions:
      id-token: write
    steps:
      -
        name: download-package
        id: download-package
        uses: actions/download-artifact@v4
        with:
          path: dist/
      -
        name: publish-pypi
        id: publish-pypi
        uses: pypa/gh-action-pypi-publish@release/v1